### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by davidmichaelakers** [OffchainLabs/arbitrum-tutorials#23]
Running either of the simple demos (using yarn run exec), results in: 

`TypeError: Only absolute URLs are supported`

**Comment by zbcoding** [comment]
I think the problem in the .env file, delete the comment and only use the private key inside quotes, without 0x in front.
e.g.
DEVNET_PRIVKEY="xxxxddddd12accc95cxxxxx85f0c7ccccc63ddd4dc5dccccc7c1dddd566ccccc"
L2RPC="https://rinkeby.arbitrum.io/rpc"
ofc Never post your real private key.

**Comment by gzeoneth** [comment]
fixed in #55
