### ISSUE TITLE
Add solidity and js linter

### ISSUE THREAD

**Issue by fredlacs** [OffchainLabs/arbitrum-tutorials#24]
The current code doesn't follow a specific style guide.

A solidity and js linter could be added

The main arbitrum repo uses this as a precommit hook
https://github.com/OffchainLabs/arbitrum/blob/338fa2da63c290faeaa27b848f1d93d60038aa09/.pre-commit-config.yaml#L53-L54

https://github.com/prettier-solidity/prettier-plugin-solidity

**Comment by gzeoneth** [comment]
Fixed in #62, didn't add a hook tho.
