### ISSUE TITLE
How Do You Verify A Contract That Was Created From The ERC20Bridger?

### ISSUE THREAD

**Issue by emoon-dev** [OffchainLabs/arbitrum-tutorials#82]
Hi - First off, great job on the token-deposit script. Ran it, and it worked great. However, I don't understand where the code that creates the bridged ERC20 contract comes from? And how does one verify the code on a tool like arbiscan?

**Comment by emoon-dev** [comment]
The crux seems to be in this code https://github.com/OffchainLabs/token-bridge-contracts/blob/2306488ba7846ceee25b4e81153f19f35959f620/contracts/tokenbridge/arbitrum/gateway/L2ERC20Gateway.sol#L89 but I don't get how one could verify it...

**Comment by mahsamoosavi** [comment]
> The crux seems to be in this code https://github.com/OffchainLabs/token-bridge-contracts/blob/2306488ba7846ceee25b4e81153f19f35959f620/contracts/tokenbridge/arbitrum/gateway/L2ERC20Gateway.sol#L89 but I don't get how one could verify it...

Hi! I'm happy you found the script useful!

The code for initializing the L2 token is here:
https://github.com/OffchainLabs/token-bridge-contracts/blob/main/contracts/tokenbridge/libraries/L2GatewayToken.sol

And the implementation verification can be done from here:
https://arbiscan.io/proxyContractChecker

**Comment by emoon-dev** [comment]
Hi - Thanks for getting back. I tried doing that on the Goerli testnet https://goerli.arbiscan.io/proxyContractChecker with a token minted from the gateway and received an error: The implementation contract at [0x2063a7def7614347896c880c0f04788de18a8deb](https://goerli.arbiscan.io/address/0x2063a7def7614347896c880c0f04788de18a8deb#code) does not seem to be verified. 

I'm guessing that contract being proxied to needs to be verified on the testnet?

**Comment by mahsamoosavi** [comment]
> > Hi - Thanks for getting back. I tried doing that on the Goerli testnet https://goerli.arbiscan.io/proxyContractChecker with a token minted from the gateway and received an error: The implementation contract at [0x2063a7def7614347896c880c0f04788de18a8deb](https://goerli.arbiscan.io/address/0x2063a7def7614347896c880c0f04788de18a8deb#code) does not seem to be verified.
> > I'm guessing that contract being proxied to needs to be verified on the testnet?
> 
> can I get the L2 address of the token you're trying to verify?

BTW, that's right! To verify the contract the etherscan needs to obtain the implementation contract first (that's why you have to get that verified first.)
 https://medium.com/etherscan-blog/and-finally-proxy-contract-support-on-etherscan-693e3da0714b

**Comment by emoon-dev** [comment]
Here is a token bridged with the script from this project: 0xD73F5688d15420dBFA66eF1E625a527955F6C157

When I enter that address here: https://goerli.arbiscan.io/proxyContractChecker 

I get the above error. You guys have the code to the proxy contract, so I was hoping you could verify it. I think this may have been done on mainnet, but not the testnet.

**Comment by mahsamoosavi** [comment]
Hey our bridge contract is now verified on arbGoerli so you should be able to verify the token you bridged.
> Here is a token bridged with the script from this project: 0xD73F5688d15420dBFA66eF1E625a527955F6C157
> 
> When I enter that address here: https://goerli.arbiscan.io/proxyContractChecker
> 
> I get the above error. You guys have the code to the proxy contract, so I was hoping you could verify it. I think this may have been done on mainnet, but not the testnet.

**Comment by emoon-dev** [comment]
Perfect!
